version: '3'
services:
  app:
    container_name : identity
    restart: always
    build: .
    command: npm start
    ports:
      - '80:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'